apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: oddbit-auth

resources:
  - keycloak/
  - postgres/

secretGenerator:
  - envs:
      - secrets/db-credentials.env
    name: db-credentials
  - envs:
      - secrets/keycloak-admin.env
    name: keycloak-admin
